version: '3.8'

services:
  appwrite:
    image: appwrite/appwrite:latest
    environment:
      - _APP_ENV=testing
      - _APP_OPENSSL_KEY_V1=$${{ secrets.APPWRITE_OPENSSL_KEY_V1 }}
      - _APP_STORAGE_DEVICE=local
      - _APP_USAGE_STATS=false
      - _APP_DOMAIN=http://localhost
      - _APP_PLATFORM_CONSOLE_HOSTNAME=http://localhost
      - _APP_DATABASE_HOST=postgres
      - _APP_DATABASE_USER=testuser
      - _APP_DATABASE_PASSWORD=testpass
      - _APP_DATABASE_NAME=testdb
    ports:
      - '80:80'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/v1']
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 2s

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=testdb
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'testuser']
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 2s
